services:
  telegram-drive-sync:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./.env:/app/.env
      - ./midias_baixadas:/app/midias_baixadas
      - ./uploads.json:/app/uploads.json
      - ./plataformas:/app/plataformas
      - ./credentials:/app/credentials
      - ./logs:/app/logs
    environment:
      - TZ=America/Sao_Paulo
    # Definir usuário com permissões apropriadas (opcional se já definido no Dockerfile)
    user: "${UID:-1000}:${GID:-1000}"
